// Author: Andreas Reiter <andreas.reiter@student.tugraz.at>
// Author: Georg Neubauer <georg.neubauer@student.tugraz.at>

using System;

namespace Iaik.Tc.TPM.Keystore
{

	public abstract class TPMKeystoreProvider : IDisposable
	{
		public TPMKeystoreProvider ()
		{
		}
		
		/// <summary>
		/// Lists all unique identifiers of all stored keys
		/// </summary>
		/// <remarks>
		/// The unique identifiers get generated by the tpm server. This
		/// identifiers are unique for all keys generated by a single tpm
		/// </remarks>
		/// <returns></returns>
		public abstract string[] EnumerateIdentifiers();
		
		/// <summary>
		/// Lists all unique friendly names of all stored keys
		/// </summary>
		/// <remarks>
		/// The friendly names are also unique, but only in the scope of
		/// this tpm keystore
		/// </remarks>
		/// <returns></returns>
		public abstract string[] EnumerateFriendlyNames();
		
		#region IDisposable implementation
		public void  IDisposable.Dispose ()
		{
		}
		#endregion
		
		
		
	}
}
